//! Packs the vendored Material Icon Theme SVGs into two generated files.
//!
//! The obvious shape — one `include_str!` per icon — is 1,251 macro
//! invocations and 1,251 separate files for rustc to open, stat and hash on
//! every build of this crate. Instead the icons are concatenated into a single
//! blob with a side table of byte ranges, so the crate carries exactly one
//! `include_str!` and the compiler sees one string literal. The binary ends up
//! with the same bytes either way; only the compile does less work.
//!
//! The blob is `str`, not `[u8]`: every file here is SVG source, and holding
//! it as text means `icon_source()` hands out `&'static str` with no
//! validation at runtime.

use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let icons_dir = manifest_dir.join("vendor/material-icon-theme/icons");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));

    // Cargo only reruns this when something under these paths changes. The
    // directory itself is listed so an added or removed icon is noticed, not
    // just an edited one.
    println!("cargo:rerun-if-changed={}", icons_dir.display());
    println!(
        "cargo:rerun-if-changed={}",
        manifest_dir
            .join("vendor/material-icon-theme/dist/material-icons.json")
            .display()
    );

    let mut sources: BTreeMap<String, String> = BTreeMap::new();
    for entry in fs::read_dir(&icons_dir).unwrap_or_else(|error| {
        panic!("vendored icons missing at {}: {error}", icons_dir.display())
    }) {
        let path = entry.expect("icon dir entry").path();
        if path.extension().and_then(|ext| ext.to_str()) != Some("svg") {
            continue;
        }
        let name = file_name(&path);
        let source = fs::read_to_string(&path)
            .unwrap_or_else(|error| panic!("reading {}: {error}", path.display()));
        println!("cargo:rerun-if-changed={}", path.display());
        sources.insert(name, source);
    }
    assert!(
        !sources.is_empty(),
        "no vendored SVGs found in {}",
        icons_dir.display()
    );

    let mut blob = String::new();
    let mut index = String::from(
        "// @generated by build.rs from vendor/material-icon-theme/icons — do not edit.\n\
         pub(crate) static MATERIAL_ICON_INDEX: &[(&str, usize, usize)] = &[\n",
    );
    for (name, source) in &sources {
        let start = blob.len();
        blob.push_str(source);
        let end = blob.len();
        index.push_str(&format!("    ({name:?}, {start}, {end}),\n"));
    }
    index.push_str("];\n");

    fs::write(out_dir.join("material_icons_blob.txt"), blob).expect("writing the icon blob");
    fs::write(out_dir.join("material_icons_index.rs"), index).expect("writing the icon index");
}

fn file_name(path: &Path) -> String {
    path.file_name()
        .and_then(|name| name.to_str())
        .unwrap_or_else(|| panic!("non-UTF-8 icon file name at {}", path.display()))
        .to_string()
}
