//! The `AgentConnection` seam — ported from `zed-ref/crates/acp_thread/src/connection.rs`.
//!
//! This is the trait every agent implements: external ACP agents (through
//! `atlas-agent-servers`) and the native agent alike. It is ported
//! near-verbatim, because it is the contract the whole UI consumes; the
//! deviations are only the ones forced by not being GPUI, and each is called out
//! at the point it appears. The catalogue of them lives in [`crate`]'s module
//! docs.

use std::any::Any;
use std::collections::HashSet;
use std::error::Error;
use std::fmt;
use std::path::PathBuf;
use std::sync::Arc;

use agent_client_protocol::schema::v1 as acp;
use anyhow::Result;
use chrono::{DateTime, Utc};
use futures::future::BoxFuture;
use indexmap::IndexMap;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use crate::{AcpThreadHandle, ElicitationStoreHandle};

/// Identifies an agent (`"claude-code"`, `"atlas-agent"`, …).
///
/// Zed's lives in its `project` crate; the port keeps a local newtype so this
/// crate stays leaf-level.
#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]
pub struct AgentId(pub Arc<str>);

impl AgentId {
    pub fn new(id: impl Into<Arc<str>>) -> Self {
        Self(id.into())
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl fmt::Display for AgentId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(f)
    }
}

impl From<&str> for AgentId {
    fn from(id: &str) -> Self {
        Self(id.into())
    }
}

impl From<String> for AgentId {
    fn from(id: String) -> Self {
        Self(id.into())
    }
}

/// A user-message ID generated by Atlas and passed to agents that support
/// client IDs.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Hash)]
pub struct ClientUserMessageId(Arc<str>);

impl ClientUserMessageId {
    pub fn new() -> Self {
        Self(Uuid::new_v4().to_string().into())
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl Default for ClientUserMessageId {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Hash)]
pub struct AgentModelId(Arc<str>);

impl AgentModelId {
    pub fn new(id: impl Into<Self>) -> Self {
        id.into()
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl AsRef<str> for AgentModelId {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}

impl fmt::Display for AgentModelId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(f)
    }
}

impl From<String> for AgentModelId {
    fn from(id: String) -> Self {
        Self(id.into())
    }
}

impl From<&str> for AgentModelId {
    fn from(id: &str) -> Self {
        Self(id.into())
    }
}

/// A login command an agent's own CLI must run in a terminal.
///
/// Zed returns `task::SpawnInTerminal` here and hands it to its terminal task
/// system (`build_terminal_auth_task`, `connection.rs:69-89`). Atlas has no such
/// task type, so the port keeps the same *fields* and lets the host decide how
/// to run it — Atlas already streams a login CLI's output into `AgentOAuthModal`.
/// Zed's `use_new_terminal` / `allow_concurrent_runs` / `hide: Always` are all
/// consequences of running inside its terminal panel and have no meaning here.
#[derive(Clone, PartialEq, Eq)]
pub struct TerminalAuthCommand {
    pub id: String,
    pub label: String,
    pub command: String,
    pub args: Vec<String>,
    /// The full environment to SPAWN this login with — the agent's own, so the
    /// login reaches the network the way the agent does. Inherited variables
    /// included, which for Atlas means the user's whole environment plus the
    /// BYOK keys read out of the keychain.
    ///
    /// Never show this to anyone. It is what a subprocess gets, not what a
    /// human should see: rendered into a shell line it would put the user's
    /// API keys on screen, on the clipboard, and in `~/.zsh_history`.
    pub env: Vec<(String, String)>,
    /// Only what the AGENT declared for this login — its `terminal.env`, or the
    /// `_meta` spec's `env`. Safe to display, and the only part a user running
    /// the command themselves actually needs: their own shell already carries
    /// the rest.
    pub declared_env: Vec<(String, String)>,
}

/// Hand-written so `env` cannot reach a log line, a panic message, or an error
/// report. The derive would have printed the user's entire environment —
/// including the BYOK keys read out of the keychain — from any `{:?}` anywhere,
/// which is precisely what this type's own doc comment forbids doing with it.
/// Nothing formats it today; this is about the next `{:?}` somebody adds.
///
/// `declared_env` is the agent's own declaration and is safe to show, so it
/// prints in full: redacting it would make the useful half unreadable to buy
/// nothing.
impl fmt::Debug for TerminalAuthCommand {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("TerminalAuthCommand")
            .field("id", &self.id)
            .field("label", &self.label)
            .field("command", &self.command)
            .field("args", &self.args)
            .field("env", &format_args!("<redacted: {} vars>", self.env.len()))
            .field("declared_env", &self.declared_env)
            .finish()
    }
}

/// Ported from `build_terminal_auth_task` (`connection.rs:69-89`).
pub fn build_terminal_auth_command(
    id: String,
    label: String,
    command: String,
    args: Vec<String>,
    env: Vec<(String, String)>,
    declared_env: Vec<(String, String)>,
) -> TerminalAuthCommand {
    TerminalAuthCommand {
        id,
        label,
        command,
        args,
        declared_env,
        env,
    }
}

/// A live connection to one agent.
///
/// Deviations from Zed, all mechanical:
/// - `Rc<Self>` → `Arc<Self>`: handlers run on tokio worker threads, so every
///   trait object here is `Send + Sync`. Zed can use `Rc` because everything
///   lives on its foreground thread.
/// - `Task<Result<T>>` → `BoxFuture<'static, Result<T>>`. Zed's `Task` is a
///   GPUI-scheduled future; boxing is the dyn-safe equivalent.
/// - Every `cx: &mut App` / `cx: &App` parameter is gone.
/// - `Entity<AcpThread>` → [`AcpThreadHandle`].
/// - `project: Entity<Project>` is gone; `work_dirs` carries what the port
///   actually needs. Atlas serves `fs/*` from disk (§D12-6), so there is no
///   project buffer store to pass.
pub trait AgentConnection: Send + Sync {
    fn agent_id(&self) -> AgentId;

    fn telemetry_id(&self) -> Arc<str>;

    fn agent_version(&self) -> Option<Arc<str>> {
        None
    }

    fn new_session(
        self: Arc<Self>,
        work_dirs: Vec<PathBuf>,
    ) -> BoxFuture<'static, Result<AcpThreadHandle>>;

    /// Whether this agent supports loading existing sessions.
    fn supports_load_session(&self) -> bool {
        false
    }

    /// Whether this agent advertised `mcpCapabilities.http` at `initialize`,
    /// i.e. whether it accepts an HTTP MCP server in `session/new`'s
    /// `mcpServers`.
    ///
    /// Session-independent, like [`Self::supports_rewind`]: it is fixed by the
    /// handshake, so it is known before any session exists. Decided only by
    /// what the agent advertised, never by which agent it is.
    fn supports_http_mcp(&self) -> bool {
        false
    }

    /// Whether this agent can drop its own last turn — see [`AgentSessionRewind`].
    ///
    /// Session-independent, like [`Self::supports_logout`], because the
    /// catalogue publishes it per agent before any session exists. It must
    /// agree with [`Self::rewind`]: this answers "would that return `Some`".
    fn supports_rewind(&self) -> bool {
        false
    }

    /// Load an existing session by ID.
    fn load_session(
        self: Arc<Self>,
        _session_id: acp::SessionId,
        _work_dirs: Vec<PathBuf>,
        _title: Option<Arc<str>>,
    ) -> BoxFuture<'static, Result<AcpThreadHandle>> {
        Box::pin(async { Err(anyhow::Error::msg("Loading sessions is not supported")) })
    }

    /// Whether this agent supports closing existing sessions.
    fn supports_close_session(&self) -> bool {
        false
    }

    /// Close an existing session. Allows the agent to free the session from memory.
    fn close_session(
        self: Arc<Self>,
        _session_id: acp::SessionId,
    ) -> BoxFuture<'static, Result<()>> {
        Box::pin(async { Err(anyhow::Error::msg("Closing sessions is not supported")) })
    }

    /// Whether this agent supports resuming existing sessions without loading history.
    fn supports_resume_session(&self) -> bool {
        false
    }

    /// Resume an existing session by ID without replaying previous messages.
    fn resume_session(
        self: Arc<Self>,
        _session_id: acp::SessionId,
        _work_dirs: Vec<PathBuf>,
        _title: Option<Arc<str>>,
    ) -> BoxFuture<'static, Result<AcpThreadHandle>> {
        Box::pin(async { Err(anyhow::Error::msg("Resuming sessions is not supported")) })
    }

    /// Whether this agent supports showing session history.
    fn supports_session_history(&self) -> bool {
        self.supports_load_session() || self.supports_resume_session()
    }

    /// Whether this agent supports additional session directories.
    fn supports_session_additional_directories(&self) -> bool {
        false
    }

    fn auth_methods(&self) -> &[acp::AuthMethod];

    fn terminal_auth_command(
        &self,
        _method: &acp::AuthMethodId,
    ) -> Option<BoxFuture<'static, Result<TerminalAuthCommand>>> {
        None
    }

    fn authenticate(&self, method: acp::AuthMethodId) -> BoxFuture<'static, Result<()>>;

    fn supports_logout(&self) -> bool {
        false
    }

    fn logout(&self) -> BoxFuture<'static, Result<()>> {
        Box::pin(async { Err(anyhow::Error::msg("Logout is not supported")) })
    }

    /// Returns a capability for agents that accept client-generated user message IDs.
    fn client_user_message_ids(&self) -> Option<Arc<dyn AgentSessionClientUserMessageIds>> {
        None
    }

    fn prompt(&self, params: acp::PromptRequest)
        -> BoxFuture<'static, Result<acp::PromptResponse>>;

    fn retry(&self, _session_id: &acp::SessionId) -> Option<Arc<dyn AgentSessionRetry>> {
        None
    }

    fn cancel(&self, session_id: &acp::SessionId);

    /// Request-scoped elicitations are connection-level because they can arrive
    /// before a session thread exists. Session-scoped elicitations stay in the
    /// thread timeline, but use [`crate::ElicitationStore`] for shared processing.
    fn request_elicitations(&self) -> Option<ElicitationStoreHandle> {
        None
    }

    fn truncate(&self, _session_id: &acp::SessionId) -> Option<Arc<dyn AgentSessionTruncate>> {
        None
    }

    fn rewind(&self, _session_id: &acp::SessionId) -> Option<Arc<dyn AgentSessionRewind>> {
        None
    }

    fn set_title(&self, _session_id: &acp::SessionId) -> Option<Arc<dyn AgentSessionSetTitle>> {
        None
    }

    /// Returns this agent as an [`AgentModelSelector`] if the model selection
    /// capability is supported, else [`None`].
    fn model_selector(&self, _session_id: &acp::SessionId) -> Option<Arc<dyn AgentModelSelector>> {
        None
    }

    fn telemetry(&self) -> Option<Arc<dyn AgentTelemetry>> {
        None
    }

    fn session_modes(&self, _session_id: &acp::SessionId) -> Option<Arc<dyn AgentSessionModes>> {
        None
    }

    fn session_config_options(
        &self,
        _session_id: &acp::SessionId,
    ) -> Option<Arc<dyn AgentSessionConfigOptions>> {
        None
    }

    fn session_list(&self) -> Option<Arc<dyn AgentSessionList>> {
        None
    }

    fn into_any(self: Arc<Self>) -> Arc<dyn Any + Send + Sync>;
}

impl dyn AgentConnection {
    pub fn downcast<T: 'static + AgentConnection + Sized>(self: Arc<Self>) -> Option<Arc<T>> {
        self.into_any().downcast().ok()
    }
}

/// Rewinding a session's history.
///
/// No implementation and no caller today — `remove_entries_from` is reached
/// only by the native agent's `/undo`. Whoever wires this up owns a coupling
/// that is not local to this file: shrinking `AcpThread::entries` makes
/// `atlas-agent-delta`'s per-session mirror shrink with it, and anything keyed
/// by entry position or by tool call id (the projector's `open_permissions`,
/// its `Projected` mirror) has to be trimmed in the same step. The projector
/// handles the `EntriesRemoved` event it already receives; check it still does
/// before assuming a new truncation path is free.
pub trait AgentSessionTruncate: Send + Sync {
    fn run(&self, client_user_message_id: ClientUserMessageId) -> BoxFuture<'static, Result<()>>;
}

pub trait AgentSessionClientUserMessageIds: Send + Sync {
    fn new_id(&self) -> ClientUserMessageId {
        ClientUserMessageId::new()
    }

    fn prompt(
        &self,
        client_user_message_id: ClientUserMessageId,
        params: acp::PromptRequest,
    ) -> BoxFuture<'static, Result<acp::PromptResponse>>;
}

pub trait AgentSessionRetry: Send + Sync {
    fn run(&self) -> BoxFuture<'static, Result<acp::PromptResponse>>;
}

/// Dropping a session's last turn and recovering the prompt that started it.
///
/// Distinct from [`AgentSessionTruncate`], which cuts at a NAMED user message
/// and so needs the [`ClientUserMessageId`] machinery nothing populates yet,
/// and from [`AgentSessionRetry`], which rewinds and re-runs as one opaque
/// step. Splitting the rewind from the re-send is what lets a caller tell a
/// rewind that landed from a send that failed — and the prompt has to come
/// back out, because after the rewind the thread no longer holds it.
///
/// `Ok(None)` means the agent declined and NOTHING changed. Anything that may
/// have left the durable history and the thread disagreeing must be an `Err`:
/// a caller told "nothing happened" cannot repair a rewind that half-happened.
pub trait AgentSessionRewind: Send + Sync {
    fn run(&self) -> BoxFuture<'static, Result<Option<String>>>;
}

pub trait AgentSessionSetTitle: Send + Sync {
    fn run(&self, title: Arc<str>) -> BoxFuture<'static, Result<()>>;
}

pub trait AgentTelemetry: Send + Sync {
    /// A representation of the current thread state that can be serialized for
    /// storage with telemetry events.
    fn thread_data(
        &self,
        session_id: &acp::SessionId,
    ) -> BoxFuture<'static, Result<serde_json::Value>>;
}

pub trait AgentSessionModes: Send + Sync {
    fn current_mode(&self) -> acp::SessionModeId;

    fn all_modes(&self) -> Vec<acp::SessionMode>;

    fn set_mode(&self, mode: acp::SessionModeId) -> BoxFuture<'static, Result<()>>;
}

pub trait AgentSessionConfigOptions: Send + Sync {
    /// Get all current config options with their state.
    fn config_options(&self) -> Vec<acp::SessionConfigOption>;

    /// Set a config option value. Returns the full updated list of config options.
    fn set_config_option(
        &self,
        config_id: acp::SessionConfigId,
        value: acp::SessionConfigOptionValue,
    ) -> BoxFuture<'static, Result<Vec<acp::SessionConfigOption>>>;

    /// Whenever the config options are updated the receiver will be notified.
    /// Optional for agents that don't update their config options dynamically.
    fn watch(&self) -> Option<tokio::sync::watch::Receiver<()>> {
        None
    }
}

#[derive(Debug, Clone, Default)]
pub struct AgentSessionListRequest {
    pub cwd: Option<PathBuf>,
    pub cursor: Option<String>,
    pub meta: Option<acp::Meta>,
}

#[derive(Debug, Clone)]
pub struct AgentSessionListResponse {
    pub sessions: Vec<AgentSessionInfo>,
    pub next_cursor: Option<String>,
    pub meta: Option<acp::Meta>,
}

impl AgentSessionListResponse {
    pub fn new(sessions: Vec<AgentSessionInfo>) -> Self {
        Self {
            sessions,
            next_cursor: None,
            meta: None,
        }
    }
}

#[derive(Debug, Clone, PartialEq)]
pub struct AgentSessionInfo {
    pub session_id: acp::SessionId,
    pub work_dirs: Option<Vec<PathBuf>>,
    pub title: Option<Arc<str>>,
    pub updated_at: Option<DateTime<Utc>>,
    pub created_at: Option<DateTime<Utc>>,
    pub meta: Option<acp::Meta>,
}

impl AgentSessionInfo {
    pub fn new(session_id: impl Into<acp::SessionId>) -> Self {
        Self {
            session_id: session_id.into(),
            work_dirs: None,
            title: None,
            updated_at: None,
            created_at: None,
            meta: None,
        }
    }
}

#[derive(Debug, Clone)]
pub enum SessionListUpdate {
    Refresh,
    SessionInfo {
        session_id: acp::SessionId,
        update: acp::SessionInfoUpdate,
    },
}

pub trait AgentSessionList: Send + Sync {
    fn list_sessions(
        &self,
        request: AgentSessionListRequest,
    ) -> BoxFuture<'static, Result<AgentSessionListResponse>>;

    fn supports_delete(&self) -> bool {
        false
    }

    fn delete_session(&self, _session_id: &acp::SessionId) -> BoxFuture<'static, Result<()>> {
        Box::pin(async { Err(anyhow::anyhow!("delete_session not supported")) })
    }

    fn delete_sessions(&self) -> BoxFuture<'static, Result<()>> {
        Box::pin(async { Err(anyhow::anyhow!("delete_sessions not supported")) })
    }

    /// Zed uses an `async_channel::Receiver`; tokio's unbounded receiver is the
    /// same single-consumer stream without pulling in a second channel crate.
    fn watch(&self) -> Option<tokio::sync::mpsc::UnboundedReceiver<SessionListUpdate>> {
        None
    }

    fn notify_refresh(&self) {}

    fn into_any(self: Arc<Self>) -> Arc<dyn Any + Send + Sync>;
}

impl dyn AgentSessionList {
    pub fn downcast<T: 'static + AgentSessionList + Sized>(self: Arc<Self>) -> Option<Arc<T>> {
        self.into_any().downcast().ok()
    }
}

/// The error every RPC maps to when the agent reports `ErrorCode::AuthRequired`.
///
/// The host matches on this to route the user into the sign-in flow, so it is
/// carried as a real `std::error::Error` rather than a string — the same reason
/// Zed does (`map_acp_error`, `agent_servers/src/acp.rs:2074-2086`).
#[derive(Debug, Default)]
pub struct AuthRequired {
    pub description: Option<String>,
}

impl AuthRequired {
    pub fn new() -> Self {
        Self { description: None }
    }

    pub fn with_description(mut self, description: String) -> Self {
        self.description = Some(description);
        self
    }
}

impl Error for AuthRequired {}
impl fmt::Display for AuthRequired {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "Authentication required")
    }
}

/// Trait for agents that support listing, selecting, and querying language models.
///
/// This is an optional capability; agents indicate support via
/// [`AgentConnection::model_selector`].
pub trait AgentModelSelector: Send + Sync + 'static {
    fn list_models(&self) -> BoxFuture<'static, Result<AgentModelList>>;

    fn select_model(&self, model_id: AgentModelId) -> BoxFuture<'static, Result<()>>;

    fn selected_model(&self) -> BoxFuture<'static, Result<AgentModelInfo>>;

    fn favorite_model_ids(&self) -> HashSet<AgentModelId> {
        HashSet::default()
    }

    fn toggle_favorite_model(&self, _model_id: AgentModelId, _should_be_favorite: bool) {}

    /// Whenever the model list is updated the receiver will be notified.
    fn watch(&self) -> Option<tokio::sync::watch::Receiver<()>> {
        None
    }

    /// Whether the model picker should render a footer.
    fn should_render_footer(&self) -> bool {
        false
    }
}

/// Icon for a model in the model selector.
///
/// Zed's `Named` variant carries a `ui::IconName` from its own icon set; the UI
/// stays in the frontend here, so the port carries the name as a string and lets
/// the renderer resolve it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum AgentModelIcon {
    Named(Arc<str>),
    Path(Arc<str>),
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AgentModelInfo {
    pub id: AgentModelId,
    pub name: Arc<str>,
    pub description: Option<Arc<str>>,
    pub icon: Option<AgentModelIcon>,
    pub is_latest: bool,
    pub cost: Option<Arc<str>>,
    /// Zed carries `language_model::DisabledReason`; that enum is about Zed's
    /// own plan/billing states, so the port carries the reason as text.
    pub disabled: Option<Arc<str>>,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct AgentModelGroupName(pub Arc<str>);

#[derive(Debug, Clone)]
pub enum AgentModelList {
    Flat(Vec<AgentModelInfo>),
    Grouped(IndexMap<AgentModelGroupName, Vec<AgentModelInfo>>),
}

impl AgentModelList {
    pub fn is_empty(&self) -> bool {
        match self {
            AgentModelList::Flat(models) => models.is_empty(),
            AgentModelList::Grouped(groups) => groups.is_empty(),
        }
    }

    pub fn is_flat(&self) -> bool {
        matches!(self, AgentModelList::Flat(_))
    }
}

#[derive(Debug, Clone)]
pub struct PermissionOptionChoice {
    pub allow: acp::PermissionOption,
    pub deny: acp::PermissionOption,
    pub sub_patterns: Vec<String>,
}

impl PermissionOptionChoice {
    pub fn label(&self) -> Arc<str> {
        self.allow.name.as_str().into()
    }

    /// Build a [`SelectedPermissionOutcome`] for this choice.
    ///
    /// If the choice carries `sub_patterns`, they are attached as
    /// [`SelectedPermissionParams::Terminal`].
    pub fn build_outcome(&self, is_allow: bool) -> crate::SelectedPermissionOutcome {
        let option = if is_allow { &self.allow } else { &self.deny };

        let params = if !self.sub_patterns.is_empty() {
            Some(crate::SelectedPermissionParams::Terminal {
                patterns: self.sub_patterns.clone(),
            })
        } else {
            None
        };

        crate::SelectedPermissionOutcome::new(option.option_id.clone(), option.kind).params(params)
    }
}

/// Pairs a tool's permission pattern with its display name.
///
/// For example, a pattern of `^cargo\s+build(\s|$)` would display as `cargo
/// build`. It's handy to keep these together rather than trying to derive one
/// from the other.
#[derive(Debug, Clone, PartialEq)]
pub struct PermissionPattern {
    pub pattern: String,
    pub display_name: String,
}

#[derive(Debug, Clone)]
pub enum PermissionOptions {
    Flat(Vec<acp::PermissionOption>),
    Dropdown(Vec<PermissionOptionChoice>),
    DropdownWithPatterns {
        choices: Vec<PermissionOptionChoice>,
        patterns: Vec<PermissionPattern>,
        tool_name: String,
    },
}

impl PermissionOptions {
    pub fn is_empty(&self) -> bool {
        match self {
            PermissionOptions::Flat(options) => options.is_empty(),
            PermissionOptions::Dropdown(options) => options.is_empty(),
            PermissionOptions::DropdownWithPatterns { choices, .. } => choices.is_empty(),
        }
    }

    pub fn first_option_of_kind(
        &self,
        kind: acp::PermissionOptionKind,
    ) -> Option<&acp::PermissionOption> {
        match self {
            PermissionOptions::Flat(options) => options.iter().find(|option| option.kind == kind),
            PermissionOptions::Dropdown(options) => options.iter().find_map(|choice| {
                if choice.allow.kind == kind {
                    Some(&choice.allow)
                } else if choice.deny.kind == kind {
                    Some(&choice.deny)
                } else {
                    None
                }
            }),
            PermissionOptions::DropdownWithPatterns { choices, .. } => {
                choices.iter().find_map(|choice| {
                    if choice.allow.kind == kind {
                        Some(&choice.allow)
                    } else if choice.deny.kind == kind {
                        Some(&choice.deny)
                    } else {
                        None
                    }
                })
            }
        }
    }

    /// Every option, whatever shape they were offered in.
    ///
    /// The wire flattens dropdown choices into a single list, so the host has
    /// to look one up the same way or an option the user was shown could not be
    /// answered.
    pub fn flattened(&self) -> Vec<&acp::PermissionOption> {
        match self {
            PermissionOptions::Flat(options) => options.iter().collect(),
            PermissionOptions::Dropdown(choices)
            | PermissionOptions::DropdownWithPatterns { choices, .. } => choices
                .iter()
                .flat_map(|choice| [&choice.allow, &choice.deny])
                .collect(),
        }
    }

    /// The option with this id, if it is one of the ones being offered.
    pub fn option_by_id(&self, option_id: &str) -> Option<&acp::PermissionOption> {
        self.flattened()
            .into_iter()
            .find(|option| option.option_id.0.as_ref() == option_id)
    }

    pub fn allow_once_option_id(&self) -> Option<acp::PermissionOptionId> {
        self.first_option_of_kind(acp::PermissionOptionKind::AllowOnce)
            .map(|option| option.option_id.clone())
    }

    pub fn deny_once_option_id(&self) -> Option<acp::PermissionOptionId> {
        self.first_option_of_kind(acp::PermissionOptionKind::RejectOnce)
            .map(|option| option.option_id.clone())
    }

    /// Build a [`SelectedPermissionOutcome`] for the `DropdownWithPatterns`
    /// variant when the user has checked specific pattern indices.
    ///
    /// Returns `Some` with the always-allow/deny outcome when at least one
    /// pattern is checked. Returns `None` when zero patterns are checked,
    /// signaling that the caller should degrade to allow-once / deny-once.
    pub fn build_outcome_for_checked_patterns(
        &self,
        checked_indices: &[usize],
        is_allow: bool,
    ) -> Option<crate::SelectedPermissionOutcome> {
        let PermissionOptions::DropdownWithPatterns {
            choices, patterns, ..
        } = self
        else {
            debug_assert!(
                false,
                "build_outcome_for_checked_patterns called on non-DropdownWithPatterns"
            );
            return None;
        };

        let checked_patterns: Vec<String> = patterns
            .iter()
            .enumerate()
            .filter(|(index, _)| checked_indices.contains(index))
            .map(|(_, cp)| cp.pattern.clone())
            .collect();

        if checked_patterns.is_empty() {
            return None;
        }

        // Use the first choice (the "Always" choice) as the base for the outcome.
        let always_choice = choices.first()?;
        let option = if is_allow {
            &always_choice.allow
        } else {
            &always_choice.deny
        };

        let outcome = crate::SelectedPermissionOutcome::new(option.option_id.clone(), option.kind)
            .params(Some(crate::SelectedPermissionParams::Terminal {
                patterns: checked_patterns,
            }));
        Some(outcome)
    }
}
